### ISSUE TITLE
Periods without set prices could be set to "Unknown" value

### ISSUE THREAD

**Issue by purcell-lab** [cabberley/HA_AemoNemData#8]
Thanks for your integration, it certainly gives me much better understanding of what is happening with prices across the NEM..

One suggestion is for periods where the price has not yet been set could be set to 'Unknown' rather than $0.0000, as $0.0000 sometimes is a valid value for a period.

![Screenshot 2024-11-22 10 46 55](https://github.com/user-attachments/assets/3f76bc8e-5131-4676-81ea-da3b3c5d5eb1)

**Comment by cabberley** [comment]
Thanks for the suggestion.
I will look at trying to change that behaviour.
Might be a week or so before have any spare time.

**Comment by cabberley** [comment]
@purcell-lab Hi Mark. I have published an updated HACS integration (2024.11.0) that defaults all values to None/Unknown instead of 0. I did a quick scan through and think I found any other values that were defaulting to aero in addition to the 5min periods.

**Comment by purcell-lab** [comment]
Excellent, thanks for the quick turn around..

![image](https://github.com/user-attachments/assets/67bf9291-8c3b-4c89-a4ef-673e43630c8d)
